### ISSUE TITLE
Can't find model 'en'

### ISSUE THREAD

**Issue by MYWmiss** [sogou/SMRCToolkit#23]
Traceback (most recent call last):
  File "E:/HDL/SMRCToolkit/run_bidafplus.py", line 21, in <module>
    reader = CoQAReader(history=-1)
  File "E:\HDL\SMRCToolkit\sogou_mrc\dataset\coqa.py", line 16, in __init__
    self.tokenizer = SpacyTokenizer()
  File "E:\HDL\SMRCToolkit\sogou_mrc\utils\tokenizer.py", line 9, in __init__
    self.nlp = spacy.load('en', disable=['parser','tagger','entity'])
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\spacy\util.py", line 136, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by Fengwills** [comment]
How did you solve it?
